// Base API instance - import this for store setup
export { baseApi as api } from './baseApi';

// Re-export all hooks from domain slices for backward compatibility
export {
  useRegisterMutation,
  useLoginMutation,
  useMeQuery,
  useGetUsersQuery,
  useCreateUserMutation,
  useUpdateUserMutation,
  useDeleteUserMutation,
} from './authApi';

export {
  useGetDashboardQuery,
  useGetAnalyticsQuery,
  useGetSmartSchedulingQuery,
} from './dashboardApi';

export {
  useGetPatientsQuery,
  useGetPatientQuery,
  useCreatePatientMutation,
  useUpdatePatientMutation,
  useDeletePatientMutation,
  useRestorePatientMutation,
  useRegeneratePatientTokenMutation,
  useGetTagsQuery,
  useCreateTagMutation,
  useDeleteTagMutation,
  useGetPatientTagsQuery,
  useAddTagToPatientMutation,
  useRemoveTagFromPatientMutation,
  useGetCustomFieldsQuery,
  useCreateCustomFieldMutation,
  useDeleteCustomFieldMutation,
  useGetPatientCustomFieldsQuery,
  useSavePatientCustomFieldMutation,
} from './patientApi';

export {
  useGetAppointmentsQuery,
  useGetAppointmentQuery,
  useGetPatientAppointmentsQuery,
  useCreateAppointmentMutation,
  useUpdateAppointmentMutation,
  useCompleteWithInvoiceMutation,
  useCancelAppointmentMutation,
  useGetAppointmentRequestsQuery,
  useApproveAppointmentRequestMutation,
  useRejectAppointmentRequestMutation,
  useGetRecurringAppointmentsQuery,
  useCreateRecurringAppointmentMutation,
  useDeleteRecurringAppointmentMutation,
  useGetWaitlistQuery,
  useCreateWaitlistEntryMutation,
  useUpdateWaitlistEntryMutation,
  useDeleteWaitlistEntryMutation,
  useBookFromWaitlistMutation,
  useGetPendingRemindersQuery,
  useTriggerRemindersMutation,
} from './appointmentApi';

export {
  useGetPatientMedicalHistoryQuery,
  useCreateVitalMutation,
  useCreateDiagnosisMutation,
  useUpdateDiagnosisMutation,
  useDeleteDiagnosisMutation,
  useCreatePrescriptionMutation,
  useUpdatePrescriptionMutation,
  useDeletePrescriptionMutation,
  useCreateAllergyMutation,
  useDeleteAllergyMutation,
  useCreateConditionMutation,
  useDeleteConditionMutation,
  useCreateMedicalRecordMutation,
  useUpdateMedicalRecordMutation,
  useGenerateVisitNoteMutation,
  useGeneratePatientSummaryMutation,
  useGetLabResultsQuery,
  useGetLabResultQuery,
  useCreateLabResultMutation,
  useUpdateLabResultMutation,
  useDeleteLabResultMutation,
  useCheckDrugInteractionsMutation,
  useCheckAllergyConflictMutation,
  useGetDoctorBriefingQuery,
} from './clinicalApi';

export {
  useGetInvoicesQuery,
  useGetUnpaidInvoicesQuery,
  useGetInvoiceQuery,
  useCreateInvoiceMutation,
  useMarkInvoiceAsPaidMutation,
  useMarkInvoiceAsUnpaidMutation,
  useGetPaymentsQuery,
  useCreateCheckoutSessionMutation,
  useRecordManualPaymentMutation,
  useGetInsuranceClaimsQuery,
  useGetInsuranceStatsQuery,
  useCreateInsuranceClaimMutation,
  useUpdateInsuranceClaimMutation,
  useDeleteInsuranceClaimMutation,
} from './billingApi';

export {
  useGetMessagesQuery,
  useGetConversationQuery,
  useSendMessageMutation,
  useGetUnreadCountQuery,
  useGetTasksQuery,
  useCreateTaskMutation,
  useUpdateTaskMutation,
  useDeleteTaskMutation,
  useGetNotificationsQuery,
  useGetNotificationUnreadCountQuery,
  useMarkNotificationReadMutation,
  useMarkAllNotificationsReadMutation,
  useDeleteNotificationMutation,
  useGetPrescriptionRequestsQuery,
  useReviewPrescriptionRequestMutation,
} from './communicationApi';

export {
  useGetPresetsQuery,
  useCreatePresetMutation,
  useCreatePresetsBulkMutation,
  useDeletePresetMutation,
  useGetNoteTemplatesQuery,
  useCreateNoteTemplateMutation,
  useDeleteNoteTemplateMutation,
  useGetClinicSettingsQuery,
  useUpdateClinicSettingsMutation,
  useSendTestEmailMutation,
  useGetDoctorRatingSummariesQuery,
  useGetDoctorRatingsQuery,
  useCreateRatingMutation,
  useGetClinicGroupQuery,
  useCreateClinicGroupMutation,
  useAddClinicToGroupMutation,
  useGetGroupAnalyticsQuery,
} from './adminApi';

export {
  useGetPortalDataQuery,
  usePortalChatMutation,
  useGetPortalMessagesQuery,
  useSendPortalMessageMutation,
  useCreatePortalPrescriptionRequestMutation,
  useCreatePublicRatingMutation,
  useGetClinicDoctorsQuery,
  useGetAvailableSlotsQuery,
  useRequestAppointmentMutation,
  useTriageSymptomsMutation,
} from './publicApi';

export {
  useGetDeviceReadingsQuery,
  useGetPatientDeviceReadingsQuery,
  useGetPatientAlertsQuery,
  useCreateDeviceReadingMutation,
  useDeleteDeviceReadingMutation,
  useGetVideoSessionsQuery,
  useGetVideoSessionQuery,
  useCreateVideoSessionMutation,
  useUpdateVideoSessionMutation,
  useGetMarketplaceItemsQuery,
  useCreateMarketplaceItemMutation,
  useUpdateMarketplaceItemMutation,
  useDeleteMarketplaceItemMutation,
  useGetMarketplaceOrdersQuery,
  useCreateMarketplaceOrderMutation,
  useUpdateMarketplaceOrderMutation,
} from './advancedApi';
